

::: {.callout-tip appearance="simple" icon=false}
##  Bibliografía de Referencia
* **Wooldridge, J. (2015).** *Introducción a la Econometría*. Cengage Learning, 5ta edición.
* **Stock, J. H. y M. Watson (2010).** *Introduction to Econometrics*. Pearson Addison-Wesley, 3ra edición.
* **Johnston, J. y J. DiNardo (2001).** *Métodos de Econometría*. Vicens-Vives, 1ra edición.
* **Greene, W. (2008).** *Econometric Analysis*. Prentice-Hall, 6ta edición.
:::


---

## I. Fundamentos del Análisis Empírico

### 1. Método Científico en Economía
 **[Apunte maestro: Datos y Causalidad](datos-causalidad.qmd)**

* Estructura de los datos en Economía.
* Análisis causal y *ceteris paribus*.

### 2. El Modelo de Regresión Lineal (MRL)
 **[Apunte maestro: Regresión Lineal y OLS](regresion-ols.qmd)**

* MRL simple vs. múltiple.
* Estimador de Mínimos Cuadrados Ordinarios (MCO/OLS) y sus propiedades.
* Teorema de Gauss-Markov.
* Intervalos de confianza y test de hipótesis.
* Predicción.

---

## II. Especificación y Robustez

### 3. Especificación y Problemas en el MRL
 **[Apunte maestro: Problemas de Especificación](especificacion.qmd)**

* Transformación de variables y relaciones no lineales.
* Selección de modelos.
* Variables binarias dependientes e independientes.
* Cambio estructural (Test de Chow).
* Multicolinealidad.
* Omisión de variables relevantes e inclusión de variables irrelevantes.
* Errores de medida.

### 4. Inferencia Causal
 **[Apunte maestro: Inferencia Causal y VI](inferencia-causal.qmd)**

* Modelo de resultados (*outcomes*) potenciales.
* Sesgo de selección.
* Estimador de Variables Instrumentales (IV) / Mínimos Cuadrados en 2 Etapas (2SLS).
    * Validez de los instrumentos.
    * Instrumentos débiles.
    * Contraste de endogeneidad.
    * Contraste de sobre-identificación.
* Estimador de Efecto Fijo (Fixed Effects).
* Estimador de Diferencias en Diferencias (Diff-in-Diff).

### 5. Heterocedasticidad y Dependencia
 **[Apunte maestro: Heterocedasticidad y GLS](heterocedasticidad-gls.qmd)**

* Causas y consecuencias.
* Contraste de heterocedasticidad.
* Contraste de autocorrelación.
* Inferencia robusta (Errores estándar robustos).

---

## IV. Datos Temporales

### 6. Series de Tiempo
 **[Apunte maestro: Series de Tiempo](series-tiempo.qmd)**

* Tendencia en el tiempo lineal y exponencial.
* Dependencia débil.
* Prueba de raíz unitaria.
* Regresión espuria.